// Copyright June Rhodes. All Rights Reserved.

#pragma once

#include "AESGCMHandlerComponent.h"
#include "RedpointEOSBuild/BuildEnvironment.h"
#include "RedpointEOSNetworking/Auth/Connection/AutomaticEncryptionCommon.h"
#include "RedpointLibHydrogen.h"

REDPOINT_EOS_CODE_GUARD_BEGIN()

namespace REDPOINT_EOS_FILE_NS_ID(3976420798, Redpoint::EOS::Networking::Auth::Connection)
{
using namespace ::Redpoint::EOS::Networking::Auth::Connection;

extern const FName AuthPhaseAutomationEncryption;

class FAutomaticEncryptionPhase : public IAutomaticEncryptionCommon
{
private:
    // Connection key/pair. Created by the server, and used for the N variant exchange.
    hydro_kx_keypair server_connection_unique_kp;

    // Client session keys. Only used on the client.
    hydro_kx_session_keypair client_session_kp;

    // Server session keys. Only used on the server.
    hydro_kx_session_keypair server_session_kp;

    // AES GCM symmetric key. Generated by server and securely passed to client.
    uint8_t AESGCMKey[FAESGCMHandlerComponent::KeySizeInBytes];

public:
    FAutomaticEncryptionPhase();
    virtual ~FAutomaticEncryptionPhase() override = default;

    virtual FName GetName() const override;
    virtual void Start(const TSharedRef<FAuthConnectionPhaseContext> &Context) override;

private:
    virtual void On_NMT_EOS_RequestClientEphemeralKey(
        const TSharedRef<FAuthConnectionPhaseContext> &Context,
        FInBunch &Bunch) override;
    virtual void On_NMT_EOS_DeliverClientEphemeralKey(
        const TSharedRef<FAuthConnectionPhaseContext> &Context,
        FInBunch &Bunch) override;
    virtual void On_NMT_EOS_SymmetricKeyExchange(
        const TSharedRef<FAuthConnectionPhaseContext> &Context,
        FInBunch &Bunch) override;
    virtual void On_NMT_EOS_EnableEncryption(const TSharedRef<FAuthConnectionPhaseContext> &Context, FInBunch &Bunch)
        override;
};

}

namespace Redpoint::EOS::Networking::Auth::Connection
{
REDPOINT_EOS_FILE_NS_EXPORT(3976420798, Redpoint::EOS::Networking::Auth::Connection, FAutomaticEncryptionPhase)
REDPOINT_EOS_FILE_NS_EXPORT(3976420798, Redpoint::EOS::Networking::Auth::Connection, AuthPhaseAutomationEncryption)
}

REDPOINT_EOS_CODE_GUARD_END()